import { Component, EnvironmentInjector, inject } from "@angular/core";
import { IonIcon, IonLabel, IonTabBar, IonTabButton, IonTabs } from "@ionic/angular/standalone";
import { addIcons } from "ionicons";
import {
	addCircleOutline,
	alertCircleOutline,
	analyticsOutline,
	arrowForward,
	arrowForwardOutline,
	barbellOutline,
	bedOutline,
	bicycleOutline,
	bookmarkOutline,
	calendarClearOutline,
	calendarOutline,
	chatboxEllipsesOutline,
	checkmarkCircleOutline,
	checkmarkOutline,
	chevronBackOutline,
	closeCircleOutline,
	documentTextOutline,
	fitnessOutline,
	flameOutline,
	flashOutline,
	giftOutline,
	homeOutline,
	infiniteOutline,
	informationCircleOutline,
	layersOutline,
	listOutline,
	mailOutline,
	notificationsOutline,
	pauseOutline,
	peopleOutline,
	personCircleOutline,
	personOutline,
	phonePortraitOutline,
	readerOutline,
	repeatOutline,
	starOutline,
	starSharp,
	stopwatchOutline,
	sunnyOutline,
	timeOutline,
	trashOutline,
	trophyOutline,
	walkOutline,
	warningOutline,
} from "ionicons/icons";

@Component({
	selector: "app-tabs",
	templateUrl: "tabs.page.html",
	styleUrls: ["tabs.page.scss"],
	standalone: true,
	imports: [IonTabs, IonTabBar, IonTabButton, IonIcon, IonLabel],
})
export class TabsPage {
	public environmentInjector = inject(EnvironmentInjector);

	constructor() {
		// TODO: Move to a new file
		addIcons({
			barbellOutline,
			timeOutline,
			chatboxEllipsesOutline,
			personOutline,
			homeOutline,
			walkOutline,
			bicycleOutline,
			layersOutline,
			repeatOutline,
			peopleOutline,
			checkmarkCircleOutline,
			calendarOutline,
			trashOutline,
			personCircleOutline,
			trophyOutline,
			mailOutline,
			phonePortraitOutline,
			documentTextOutline,
			fitnessOutline,
			giftOutline,
			notificationsOutline,
			sunnyOutline,
			flameOutline,
			addCircleOutline,
			arrowForwardOutline,
			pauseOutline,
			infiniteOutline,
			bedOutline,
			calendarClearOutline,
			checkmarkOutline,
			closeCircleOutline,
			chevronBackOutline,
			analyticsOutline,
			arrowForward,
			informationCircleOutline,
			alertCircleOutline,
			stopwatchOutline,
			listOutline,
			readerOutline,
			flashOutline,
			warningOutline,
			bookmarkOutline,
			starSharp,
			starOutline,
		});
	}
}
